### ISSUE TITLE
嗨！由于你的博客没有留言功能，因此我发留言到这里了

### ISSUE THREAD

**Issue by swarm413** [mikexfreeze/mikexfreeze.github.io#1]
亲爱的朋友：
你好！博客做的非常美观，UI设计绝对是达标了，同时博客里面的内容体现了深刻的洞察力与思辩力。
由于技术不同的原因，我并没有观看你的技术文章，而是看了2020年中房价分析这篇文章。
坦白的说，很高兴能欣赏到这样有思想的文章。
我也认为房产税势在必行，并且房产税的目的不在于控制房价上涨而在于扩大地方财政税收来源。很高兴与你不谋而合。
工业化时期，财政税收的主要来源是农民，即工农剪刀差。后2002年废除农业税绝对不是因为恩赐，而是因为有了新的税收来源，且农业税份额过低
城市化进程期间，财政税收的主要来源就是进城务工人员，房价的主要推手的地方政府而不是房地产商。就目前地方债务情况来看，扩大税收刻不容缓
但是有一点你我的观点存在分歧，实际上房产税会加重房屋租金，“_从南京某小区采样举例 165w 的房子租金 3000，租售比 46。按照国际上合理的租售比 30 来计算，合理的价格应在 108w。_”遗憾的是，你预测未来房价会降低，但是我预测未来房租会升高。
最后，很高兴看到你具有国际化视野，同比观察了日本美国等发达国家的发展路径。其实，不难看出，未来中国小城市空心化是必然，而一线大城市房价只会增不会减

**Comment by mikexfreeze** [comment]
朋友你好：
博客美观谬赞了，用的别人做的模板🙂。博客应当是有留言功能的。见下图，如果确实没有我要去查查问题了。感谢您来这里回复。

写下此文的时候我是认为未来几年房价有下降趋势。房产税开征之后有大的下降趋势。但之后疫情发生形势有了很大的变化。
现在我认为还需要具体问题具体分析。具体内容可能又够写一篇文章了。
对于您认为房产税会加重房屋租金升高的观点我并不反对。实际上国外就发生过这样的情况。但我认为需要有些限定条件，人口净流入，GDP增长速度处于前列的城市，优质商品房。

_“其实，不难看出，未来中国小城市空心化是必然”_  同意。
_“一线大城市房价只会增不会减”_ 部分同意，还是要具体问题具体分析。上海深圳这样的城市，豪宅价格还能继续上涨。但是普通住宅并不绝对。因其价格已经达到或超过普通市民所能承受的上限。势必会倒逼人才的外流影响城市发展。但如果需要给出结论的话还是要设定很多条件，时间，区域等等。就算一个城市也不能一概而论。

再次感谢，承蒙欣赏，来此留言。
![image](https://user-images.githubusercontent.com/16068816/114138113-b8f53880-993f-11eb-8d1c-e5c398c078f4.png)

**Comment by swarm413** [comment]
哈哈。其实北京的房价就不会跌，这点完全可以参考东京，首尔，台北

**Comment by swarm413** [comment]
另外您太把群众当回事了，群众口袋里面没有钱，为什么房价还会不断上涨呢？这不符合市场规律啊。因为房产交易的交易双方中，几乎见不到群众的身影
